import Content from "./Components/Content";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Content>
          {children}
        </Content>
      </body>
    </html>
  );
}
